apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql-pod
spec:
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_PASSWORD
              value: redhat
            - name: MYSQL_ROOT_PASSWORD
              value: redhat
            - name: MYSQL_USER
              value: devenes
            - name: MYSQL_DATABASE
              value: phonebook
          ports:
            - containerPort: 3306