apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database-app
  labels:
    app: mysql 
    enviornment: database
spec:
  selector:
    matchLabels:
      app: mysql 
      enviornment: database
  template:
    metadata:
      labels:
        app: mysql 
        enviornment: database
    spec:
      containers:
      - name: mysql-database-app
        image: mysql:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysql-database-app-secret
                key: password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-database-app-secret
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-database-app-secret   # secret name 
                key: password      # secret value of key 
          - name: MYSQL_DATABASE
            value: phonebook
        volumeMounts:
        - name: datastore
          mountPath: /var/lib/mysql/ 
      volumes:
      - name: datastore
        persistentVolumeClaim: 
          claimName: database-pvc-uses
          
