apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-vol
  labels:
    app: mysql 
    enviornment: database
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-uses
  labels:
    app: mysql 
    enviornment: database
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce