apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: result-app-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app-pod
  template:
    metadata:
      labels:
        app: result-app-pod
    spec:
      imagePullSecrets:
        - name: ecr-login
      containers:
        - name: result-app
          image: 605134434853.dkr.ecr.ap-south-2.amazonaws.com/microservice:result_server_imageid_2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: result-app-secret
                  key: password
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_DATABASE
              value: phonebook
            - name: MYSQL_DATABASE_HOST
              value: mysql-database-app-svc.default.svc.cluster.local
          resources:
            limits:
              cpu: 1
              memory: "2G"
            requests: 
              cpu: "500m" 
              memory: "1G"